name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
        - cat /etc/*-release
        - dnf upgrade -y >/dev/null && echo OK
        - dnf install -y python37 >/dev/null && echo OK
        - dnf install -y fedora-workstation-repositories >/dev/null && echo OK
        - dnf install -y 'dnf-command(config-manager)' >/dev/null && echo OK
        - dnf config-manager --set-enabled google-chrome >/dev/null && echo OK
        - dnf install -y google-chrome-stable >/dev/null && echo OK
        - pip3 install webdrivermanager >/dev/null && echo OK
        - webdrivermanager chrome >/dev/null && echo OK
        - pip3 install robotframework robotframework-seleniumlibrary | grep "Successfully installed"
        - python --version
        - google-chrome --version
        - chromedriver --version


  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
    - run: robot TestCasesBDD2Easy.robot
